/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1UqaskX1BNZ
 */
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { ScrollArea } from "@/components/ui/scroll-area"



export default function Youtube() {
  return (
    <div className="grid gap-4 w-full max-w-2xl mx-auto p-4">
      <h1 className="text-2xl font-bold text-center">YouTube Hashtag Generator</h1>
      <p className="text-gray-500 dark:text-gray-400 text-center">
        Enter your video script and we'll generate relevant hashtags for you.
      </p>
      <div className="grid gap-2">
        <Label htmlFor="script">Your Video Script</Label>
        <Textarea id="script" placeholder="Enter your video script here..." />
      </div>
      <Button className="w-full">Generate Keywords</Button>
      <Card className="h-full">
        <CardHeader>
          <CardTitle>Generated Keywords</CardTitle>
          <CardDescription>These are the keywords generated from your script.</CardDescription>
        </CardHeader>
        <CardContent className="text-sm">keyword1, keyword2, keyword3, keyword4, keyword5</CardContent>
      </Card>
      <div className="grid gap-2">
        <Label htmlFor="hashtags">Enter your keyword</Label>
        <Input id="hashtags" placeholder="Enter your comma seperated keywords here ..." />
      </div>
      <Button className="w-full">Generate Hashtags</Button>

      <h1 className="text-3xl font-bold text-white">Similar Hashtags</h1>
      <p className="text-sm text-gray-600">The hashtags that contain similar keyword.</p>
      <div className="mt-6 grid grid-cols-1 md:grid-cols-3 gap-6">
        <div>
          <div className="flex justify-between items-center mb-2">
            <h2 className="text-lg font-semibold text-gray-100">Frequent</h2>
            <Badge variant="secondary">HARD</Badge>
          </div>
          <ScrollArea className="h-72 rounded-md border bg-white text-black p-4">
            <p >#engineering #engineeringlife #engineeringstudent</p>
          </ScrollArea>
        </div>
        <div>
          <div className="flex justify-between items-center mb-2">
            <h2 className="text-lg font-semibold text-gray-100">Average</h2>
            <Badge variant="secondary">MEDIUM</Badge>
          </div>
          <ScrollArea className="h-72 rounded-md border bg-white text-black p-4">
            <p>#softwareengineering #engineeringpost #engineeringgirls</p>
          </ScrollArea>
        </div>
        <div>
          <div className="flex justify-between items-center mb-2">
            <h2 className="text-lg font-semibold text-gray-100">Rare</h2>
            <Badge variant="secondary">EASY</Badge>
          </div>
          <ScrollArea className="h-72 rounded-md border bg-white text-black p-4">
            <p>#engineering_trolls #engineeringmemes #engineeringdesign</p>
          </ScrollArea>
        </div>
      </div>
      <div className="mt-8 bg-white p-6 rounded-lg shadow-md">
        <div className="flex justify-between items-center mb-4">
          <h2 className="text-lg font-semibold text-gray-900">Select hashtags</h2>
          
        </div>
        <div className="flex flex-col space-y-4">
          <div className="flex items-center">
           
            <span className="ml-2 text-gray-700">
              #engineering #engineeringstudent #softwareengineering #engineeringpost #engineeringgirls
              #engineering_trolls
            </span>
          </div>
          <div className="flex items-center justify-between">
            <Button variant="outline">Copy</Button>
          
          </div>
        </div>
      </div>
      <div className="mt-6 flex justify-center">
        <div className="flex space-x-2">
          <PlayIcon className="text-gray-500" />
          <AppleIcon className="text-gray-500" />
        </div>
      </div>
    </div>
  )
}
function AppleIcon(props) {
    return (
      <svg
        {...props}
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M12 20.94c1.5 0 2.75 1.06 4 1.06 3 0 6-8 6-12.22A4.91 4.91 0 0 0 17 5c-2.22 0-4 1.44-5 2-1-.56-2.78-2-5-2a4.9 4.9 0 0 0-5 4.78C2 14 5 22 8 22c1.25 0 2.5-1.06 4-1.06Z" />
        <path d="M10 2c1 .5 2 2 2 5" />
      </svg>
    )
  }
  
  
  function PlayIcon(props) {
    return (
      <svg
        {...props}
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <polygon points="5 3 19 12 5 21 5 3" />
      </svg>
    )
  }
  
  
  function TwitterIcon(props) {
    return (
      <svg
        {...props}
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
      </svg>
    )
  }
  