/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/kYtx2AdD1jL
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import Link from 'next/link';


export default function Card1() {
  return (
    <div className="dark bg-black text-white min-h-screen p-4 md:p-8 flex items-center justify-center">
      <div className="grid md:grid-cols-2 gap-4 md:gap-8">
        <Card className="h-full w-full max-w-md">
          <CardHeader className="flex flex-row items-center">
            <YoutubeIcon className="mr-2 text-red-500 w-8 h-8" />
            <div className="grid gap-1.5">
              <CardTitle>YouTube Hashtag Generator</CardTitle>
              <CardDescription>Generate the most effective hashtags for your YouTube videos.</CardDescription>
            </div>
          </CardHeader>
          <CardContent />
          <CardFooter>
          <Link href="/youtube">
    
            <Button className="w-full">Get started on YouTube</Button>
  
           </Link>
          </CardFooter>
        </Card>
        <Card className="h-full w-full max-w-md">
          <CardHeader className="flex flex-row items-center">
            <InstagramIcon className="mr-2 text-pink-500 w-8 h-8" />
            <div className="grid gap-1.5">
              <CardTitle>Instagram Hashtag Generator</CardTitle>
              <CardDescription>Generate the most effective hashtags for your Instagram posts.</CardDescription>
            </div>
          </CardHeader>
          <CardContent />
          <CardFooter>
          <Link href="/instagram">
            <Button className="w-full">Get started on Instagram</Button>
          </Link>
          </CardFooter>
        </Card>
      </div>
    </div>
  )
}


function YoutubeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2.5 17a24.12 24.12 0 1 0-10 2 1.4-1.4 49.56 16.2 0A2 21.5 7a24.12 10 1-1.4 1.4 49.55 1-16.2 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>
  )
}


function InstagramIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 12.63 8 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}
