/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1UqaskX1BNZ
 */
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function ytcard() {
  return (
    <div className="grid gap-4 w-full max-w-2xl mx-auto p-4">
      <h1 className="text-2xl font-bold text-center">YouTube Hashtag Generator</h1>
      <p className="text-gray-500 dark:text-gray-400 text-center">
        Enter your video script and we'll generate relevant hashtags for you.
      </p>
      <div className="grid gap-2">
        <Label htmlFor="script">Your Video Script</Label>
        <Textarea id="script" placeholder="Enter your video script here..." />
      </div>
      <Card className="h-full">
        <CardHeader>
          <CardTitle>Generated Keywords</CardTitle>
          <CardDescription>These are the keywords generated from your script.</CardDescription>
        </CardHeader>
        <CardContent className="text-sm">#keyword1, #keyword2, #keyword3, #keyword4, #keyword5</CardContent>
      </Card>
      <div className="grid gap-2">
        <Label htmlFor="hashtags">Your Hashtags</Label>
        <Input id="hashtags" placeholder="Enter your hashtags here..." />
      </div>
      <Button className="w-full">Generate Hashtags</Button>
    </div>
  )
}
